### ISSUE TITLE
.checkignore file seems ignored by QC

### ISSUE THREAD

**Issue by vasily-v-ryabov** [quantifiedcode/issues#6]
My project on QC: https://www.quantifiedcode.com/app/project/6d66337b96ed4cb1b01574ec3d39f9e7

My .checkignore file on GitHub repo: https://github.com/pywinauto/pywinauto/blob/master/.checkignore

This file seems not used by QC to exclude files from analysis. Organization and user name mismatch may be a reason, because I logged on QC as a user, but the repo is inside an organization.

**Comment by MrLeeh** [comment]
I got the same problem here. I want to exclude two files from being checked by Quantified Code. But it doesn' t have any effect.

QC repository: https://www.quantifiedcode.com/app/project/c09bff5bdc1f466b92361ce25fead1d5
github repository: https://github.com/MrLeeh/pdftools

My **.checkignore** file:
```python
versioneer.py
pdftools/_version.py
```

**Comment by vasily-v-ryabov** [comment]
When I add more rights to QC app for organization, some issues for ignored files are gone. But currently there are still 6 "potential bug" issues (six.py, sandbox/*) in my project that should be ignored: https://www.quantifiedcode.com/app/project/gh:pywinauto:pywinauto

**Comment by adewes** [comment]
Hey Vasily,

thanks for reporting this, we are working on a fix!

Cheers
Andreas

**Comment by vasily-v-ryabov** [comment]
Well. It works much better now. But I still see 2 ignored files (sandbox/_DrawDialog_win32_1.py and sandbox/_DrawDialog_Wx.py) in "Avoid using wildcard imports" section and 1 ignored file (sandbox/DemiTest.py) in "Avoid accessing protected class members from outside" section.

It looks like there are still some cases to fix.

**Comment by CarstVaartjes** [comment]
For me it still doesn't work at all. And that's with a fairly simple .checkignore file with:

    customer_specific/
    docs/
    requirements/
    script/
    upgrades/
    tests/

**Comment by CarstVaartjes** [comment]
Update, See: https://github.com/visualfabriq/bquery/blob/master/.checkignore

So i've tried all these patterns:


    # standard
    bquery/benchmarks/
    bquery/tests/
    # other try
    bquery/benchmarks
    bquery/tests
    # try with wildcards
    bquery/benchmarks/*
    bquery/tests/*
    # try with recursive wildcards
    bquery/benchmarks/**
    bquery/tests/**

All of these still give me errors from underlying directories such as bquery/benchmarks/vbench. Aren't recursive ignore possible?

**Comment by programmdesign** [comment]
@CarstVaartjes @adewes is on it. I'm positive it's fixed soon.

**Comment by CarstVaartjes** [comment]
Great! Thanks, already took a subscription too :)

**Comment by programmdesign** [comment]
@CarstVaartjes @MrLeeh @vasily-v-ryabov  We deployed a fix for this issue. For our repos, all worked find. Can you confirm? 

- Add a .checkignore file to your repo
- Click on "Check for new commits" on your project page
- Once the analysis is finished, refresh the page in your browser

@CarstVaartjes: thanks for the subscription. Glad you couldn't wait ;-)

**Comment by vasily-v-ryabov** [comment]
Thanks for your efforts guys! Now it works again.

But there is one issue: 2nd level subfolder seems not recognized by your algorithm.

[.checkignore file](https://github.com/pywinauto/pywinauto/blob/master/.checkignore) contains `pywinauto/unittests/` line, but QC still shows orange warnings for this subfolder.

For example, [Avoid "non-Pythonic" method names](https://www.quantifiedcode.com/app/project/gh:pywinauto:pywinauto?groups=code_patterns%3A2QdgB8ll%3Ap1) section shows a lot of `unittests` files.

**Comment by vasily-v-ryabov** [comment]
Oh, and `doc_src/` line doesn't work as well.
Only `pywinauto/six.py` line really works.

**Comment by adewes** [comment]
Hey Vasily,

thanks for checking again. I just reset the project so that it's analyzed
again, afterwards the files should no longer appear. QC does not reanalyze
commits that it already has analyzed, which is probably why you still see
those files. We're still working on a better solution for this, so if you
have any suggestions or ideas for further improvements please let us know,
will be happy to discuss.

Best
Andreas

**Comment by vasily-v-ryabov** [comment]
OK, now it looks like the problem is how the analysis is done.
I expect that .checkignore file is applied to the whole repo, but in fact it's applied for all commits after the .checkignore file was created. Correct?

**Comment by programmdesign** [comment]
.checkignore is applied on any commit or re-analysis. Not just for commits after the .checkignore was added. I think the fact that your file are not ignored has to do with the notation in the .checkignore file. I'll create a fork later and test this.

**Comment by programmdesign** [comment]
@vasily-v-ryabov: I opened a pull request for pywinauto that should should do the trick. As far as I can see, the .checkignore settings in my fork are now working fine: https://www.quantifiedcode.com/app/project/4ff99ffbd2164fd99f0d2dcf126c9003?tab=basics

**Comment by vasily-v-ryabov** [comment]
@programmdesign, thank you for the fix. Now it's working fine!

It's not so obvious [in the docs](http://docs.quantifiedcode.com/configuration/config_checkignore.html) that folder name should trail with `*` after `/`. My previous experience with codecov.io service shown that `*` is not necessary, but you require that. I think this rule might be more flexible. That's only my opinion.

If you are about leaving it as it is, please add one more line to the docs example:
```
# Exclude the whole subfolder
tests/*
```
I believe it makes the feature description more clear.

Thank you for all your help, guys!

**Comment by programmdesign** [comment]
Thanks for your patience. Will make the settings there easier. I already updated the docs. They'll be updated with the next deployment.

**Comment by CarstVaartjes** [comment]
Thanks so much for the quick response! I'm using the ** (also exclude subfolders) which seems work! :+1:
